export type SearchFunction = 'SYMBOL_SEARCH' | 'TIME_SERIES_INTRADAY' | 'TIME_SERIES_DAILY' | 'TIME_SERIES_WEEKLY' | 'TIME_SERIES_MONTHLY' | 'OVERVIEW' | 'TIME_SERIES_INTRADAY';

export type Interval = '5min';